### PR TITLE
(7.x.x) font material as re-useable chunks

### PR DESCRIPTION
**Pull request by swingingtom**
This PR is part of MaterialManager refactor, targeting text components.

It offers rendering chunks that compose materials. Those chunks work on three-mesh-ui core materials and also on three materials.

That PR also standardize uniforms names with three materials; color instead of u_color, easing the re-using of three materials for customisation.

### CODE REVIEW

**Comment by swingingtom** [comment]
Looks like I rebased that branch on itself... What an achievement !

**Comment by swingingtom** [comment]
New examples ( that still need to be cleaned and improved, suggestions welcome )

- [.invertAlpha](https://felixmariotto.github.io/three-mesh-ui/7.x.x/#api__invert_alpha) ( new property, works as webglpreprocessor on material )
- [Custom Materials (msdf)](https://felixmariotto.github.io/three-mesh-ui/7.x.x/#ex__msdf_materials) ( custom made and some are provided from examples folder)
- [Text Shadows](https://felixmariotto.github.io/three-mesh-ui/7.x.x/#ex__msdf_shadows) (msdf material and customDepthMaterial on Text)
- [Text Geometry Alter](https://felixmariotto.github.io/three-mesh-ui/7.x.x/#ex__msdf_crumple) (Hook FontVariant to modify geometries before they are sent )

**Comment by felixmariotto** [comment]
These news examples look really good ! Especially [this one](https://felixmariotto.github.io/three-mesh-ui/7.x.x/#ex__msdf_crumple), I love it.

**Comment by swingingtom** [comment]
Hey @felixmariotto ! Glad to hear from you. 
<3 Thank you, I really appreciate... Especially that that #@!@#$@ ToonMaterial took me too much time...

> Thanks a lot, you're really bringing it to the next level ! 

Globally the base was really good, which ease the current roadmap. Hopefully at the end it will stay that good.

**Pull request merged**
