### PR TITLE
Feature/justification spacing

### PR DESCRIPTION
**Pull request by swingingtom**
Addressing #25 

Added justify-content : `space-around` , `space-between`, `space-evenly`

The implementation take the remaining space to distribute it accross children according to the defined value.

**Example :** 
Show for both content directions `row` and `column` the following justify-content property : `start`, `end`, `center`, `space between`, `space-around', `space-evenly`. 

It intervally alter alignContent to : `start`, `end`, `center`
It intervally change `row` to `row-reverse` and `column` to `column-reverse`
It intervally change the size of justified items. 

image

Some related topics:

## start end confusion
When coding the interval to change `row` to `row-reverse`, I was a bit confuse because it didn't behave as I would have expected. The current justifyContent `end`/`start` implementations act as `flex-end` and `flex-start` in css. 

In terms of layouting possibilities, it doesn't have any impacts, as users still could manually inverse the justifyContent when direction is `-reverse`  in order to have the expected behaviour.

## Align of space-*
Alignment of `space-between`, `space-around`, `space-evenly` is currently on `{flex-}start`. Which means if children size is greater than inner, instead of being distributed, those property would stick to `start`

I still ask, but should we overlap items if the container is too narrow?

## Align content
I currently added `start`,`end` as valid align content values. It offers the ability to be used either in `column` or `row` direction.

When I onboarded with this library, I was trying to change my tests layouts from `row` to `column` and I found it a bit exhaustive to also require to update alignContent property accordingly. This led me to many warning when flipping layout direction.

But my current changes allowed me to notice that inlines also relies on `alignContent`. It provides the textAlign behaviour if I understood it correctly. So the proposition might not fit perfectly right now

## Warnings
Warnings are globally triggered during update when invalid value in context(row-column), or unavailable value. This can lead to performance downgrade and are triggered even when no direct set on the invalid property in done.

Could we dispatch warnings during `set()` instead?  and fallbacking to another valid value instead? This could save some warning during further update and keep user informed.

## Code location
As this is increasing `BoxComponent` source, and possibly related to `InlineManager` I wonder it would be better to place it in its own, just like `Whitespace.js`.

### CODE REVIEW

**Comment by felixmariotto** [comment]
Great work !

The demo is pretty costly though. I know it's cool to see an animation of the different setups, but there is `layoutUpdates` for a lot of elements every frames here, so when I try the demo on my Oculus Quest it's running at 20FPS...

If we remove the right panel with the column layouts, we get 40FPS on the Quest.
We could also animate with steps, like [this example](https://felixmariotto.github.io/three-mesh-ui/#letter_spacing).

**Comment by swingingtom** [comment]
@felixmariotto when removing small texts "A-B-C-D-E", in my computer a frame drops from ~12ms to ~4ms. 
If you could provide your quest fps with this setup, this would be interesting.

The current demo state is more a global development overview than a real feature demonstration. The ideal final example could be interactive, and display buttons to switch layout, align and size.

**Comment by swingingtom** [comment]
Hey, sorry for the delay, was unavailable the full week. Ready to resume to PR, which direction would it take in your opinion?

**Comment by swingingtom** [comment]
@felixmariotto According to what have been told on #168 , I tried splitting `alignContent`. 

I was able to deprecate and split `alignContent` property without real breaking changes. All examples are still working without changes, except best-fit which is not centered anymore ( trivial ). 

Deprecation [warns and overrides](https://github.com/swingingtom/three-mesh-ui/blob/5acbd8398c58b58ba1b708a6e3a827229f00f07e/src/components/core/MeshUIComponent.js#L457). Which still could degrade performances if `alignContent` is set on every frame. I did that on [another branch](https://github.com/swingingtom/three-mesh-ui/tree/feature/split-align-content).

What do you think?

Additional text alignments could also be easily done after splitting.
image

**Comment by swingingtom** [comment]
## `alignContent`
`alignContent` **has been removed** and splitted to `alignItems` & `textAlign` with deprecation warnings and fallbacks which should still allows existing codebases to work. Or at least don't break.

Those deprecation could be removed on 7.x.x

### `alignItems` 
Same as css `align-items` with available values :  
- `start` 
- `end` 
- `center` : **default value**
- `stretch` : _working but poor codebase that should be refactored_
- _`left` : **Deprecated**, fallback on `start` when `contentDirection` is `'row'`_
- _`right` : **Deprecated**, fallback on `end` when `contentDirection` is `'row'`_
- _`top` : **Deprecated**, fallback on `start`  when `contentDirection` is `'column'`_
- _`bottom` : **Deprecated**, fallback on `end` when `contentDirection` is `'column'`_

Those deprecation could be removed on 7.x.x

### `textAlign` 
Same as css `text-align` with available values :  
- `left`
- `right` 
- `center` : **default value**
- `justify` : _please note that it acts as **`justify-all`** in css_
- `justify-left` : `justify` except that last line is `left`
- `justify-right` : `justify` except that last line is `right`
- `justify-center` : `justify` except that last line is `center`

### `justifyContent`
- `start` : _please note that it acts as **`flex-start`** in css_
- `end` : _please note that it acts as **`flex-end`** in css_
- `center` : **default value**
- `space-between` : ADDED
- `space-around` : ADDED
- `space-evenly` : ADDED

**Pull request merged**
