### PR TITLE
improve best_fit example

### PR DESCRIPTION
**Pull request by felixmariotto**
Some slight improvements of the new best-fit example : 
- panels centered in the scene
- borders
- rounded edges
- more contrasting colors for readability
- enable stats

Screenshot_3

### CODE REVIEW

**Review by GoncaloBastos — APPROVED** [review]
The example looks much better now.

**Comment by felixmariotto** [comment]
It's a matter of taste I guess but I can't stand sharp corner, idk why...

**Comment by swingingtom** [comment]
> It's a matter of taste I guess but I can't stand sharp corners, idk why...

That's good to know for further PR, faster approvals with rounded corners :)

As much as the orange border adds some warning precautions, the dark borders looks a bit cartoon IMO... 

> It's a matter of taste...

**Comment by felixmariotto** [comment]
@swingingtom sorry I was too quick to merge... Looks like I have to learn to be more patient

**Pull request merged**
