### PR TITLE
(7.x.x) Development / Examples : Automatically register example files 

### PR DESCRIPTION
**Pull request by swingingtom**
This PR remove the needs of adding and maintaining the example array in webpack.config file
```javascript
const pages = [
	[ 'api__align_items', '.alignItems' ],
	[ 'api__antialiasing', '.fontSuperSampling' ],
	[ 'api__background_size', '.backgroundSize' ],
	[ 'api__border', '.border-<sup>*</sup>' ],
	[ 'api__content_direction', '.contentDirection' ],
	[ 'api__font_kerning', '.fontKerning' ],
	[ 'api__hidden_overflow', '.hiddenOverflow' ],
	[ 'api__invert_alpha', '.invertAlpha<sup>(msdf)</sup>' ],
	[ 'api__justify_content', '.justifyContent' ],
	[ 'api__letter_spacing', '.letterSpacing' ],
	[ 'api__manual_positioning', '.autoLayout' ],
	[ 'api__text_align', '.textAlign' ],
	[ 'api__whitespace', '.whiteSpace' ],
	[ 'tut__basic_setup', 'Basic setup' ],
	[ 'tut__basic_setup_7xx', 'Basic setup 7xx' ],
	[ 'tut__preloaded_font', 'Preload fonts' ],
	[ 'tut__preloaded_font_7xx', 'Preload fonts 7xx' ],
	[ 'tut__nested_blocks', 'Nested Blocks' ],
	[ 'tut__sizes', 'Sizes' ],
	[ 'tut__tutorial_result', 'Tutorial result' ],
	[ 'ex__best_fit', 'BestFit<sup>(behavior)</sup>' ],
	[ 'ex__bounds_uv', 'Bounds UV<sup>(behavior)</sup>' ],
	[ 'ex__frame_materials', 'Frame Materials' ],
	[ 'ex__interactive_button', 'Interactive Button' ],
	[ 'ex__msdf_crumple', 'MSDF Crumple' ],
	[ 'ex__msdf_materials', 'Font Materials<sup>(msdf)</sup>' ],
	[ 'ex__msdf_shadows', 'Font Shadows<sup>(msdf)</sup>' ],
	[ 'ex__msdf_text', 'Big Text' ],
	[ 'ex__inline_block', 'Inline Block' ],
	[ 'ex__onafterupdate', 'On after Update' ],
	[ 'ex__keyboard', 'Keyboard' ],
	[ 'dev__border_units', 'Border units' ],
	[ 'dev__border_width', 'Border Width' ],
	[ 'dev__baseline', 'Character Alignment' ],
	[ 'dev__frames', 'Frames' ],
	[ 'dev__justification', 'Justification' ],
	[ 'dev__padding', 'Padding' ],
	[ 'dev__test_preparation', 'TestPrepa' ],
	[ 'dev__queryselector', 'QuerySelector' ],
	[ 'dev__whitespace', 'WhiteSpace' ],
];
```
was reduced to
```javascript
// Automatically get all example.js files
const entryPoints = {};
glob.sync( './examples/*.js' ).map( function ( file ) {
	const entryKey = path.basename( file, '.js' );
	entryPoints[ entryKey ] = file;
} );
```

In order to not loose informations ( previously in the array, the entry point but also a nice title was defined ) I added meta data in example files. Those metadata are parsed during webpack built and injected into templates.

This is what it looks in files
xfg-source

And this is the rendering
xfg-render

Currently I only updated api__align_items.js but could do more if accepted.

While working, the current implementation looks messy, as logic and plugin are now parts of the webpack,config-prod.js file. 

Any thoughts ?

@felixmariotto I pm you about this, regarding king of informations you would like to display on example files.

### CODE REVIEW

**Comment by felixmariotto** [comment]
It looks good to me !
I'm a bit wary of seeing the list of devDependencies growing though, we are still at an acceptable level but let's be careful. A bit of code duplication is more manageable than being stuck in dependency hell.

**Comment by swingingtom** [comment]
Thats a good point. 
It might be better to start it asap.

Can you point out which dependencies you would put as libs ?

**Comment by felixmariotto** [comment]
> Can you point out which dependencies you would put as libs ?

I'm not sure what half of them do to be honest, they were added while I was busy (sorry).
Where is `babel` used exactly ? It seems it's not used in the webpack config files ?
What is `acorn`, and why do we need that ?
In the 7.x.x branch, I see that you added tests, that's great. I don't use `karma`, are all those dependencies necessary ? Maybe they are I don't know, just asking. Also `chai` and `mocha` ? Anyway if it's all for tests it's not that important, if it ever comes to dependency hell we could just drop the tests and rewrite them without having to worry about three-mesh-ui core files (unless you added meta data for tests in the core ?).
About `glob`, is it really necessary, or is there a way to use nodejs `fs` instead ?
About `typescript`, I personally never use that but if you think it's a good idea okay. I just would like to know, is there a risk that it causes conflicts with webpack or the other building tools if we don't upgrade them ?

I know it's just the current standard, but sometimes I wonder why it must be so complex to build a project in JavaScript, it's not even a compiled language but somehow it's now more complex to compile than C++

**Comment by swingingtom** [comment]
## tsc

Because it's not C++ but Javascript, editors and IDE have to guess. A LOT. About everything. 
Javascript wasn't my first professional language and I used to have strong types. They provide as much as possible "compiling errors" prior and instead of only "runtime error". 

So people brought tools to improve this behavior in javascript. We had coffeescript, typescript, etc... They both provides reliability by reducing as much as possible editor guesses, but they need to have a basis to be able to tell you : 

```javascript
// Editor should yell : 
// "Dude, I refuse to compile this thing! Don't even waste your time to run/test it!"
// "You need a number to obtain a squareRoot !"
const i = getSquareRoot( "Bob" );
```
Basis for editors to know rules to respect can be as simple as JSDOC

```javascript
/**
 * 
 * @param {Vector4} vector4
 * @param {string|number|Array.<string|number>} value
 * @private
*/
_fourDimensionsValueSetter( vector4, value ) { }
```
With this documentation above the function, editors will be then able to provides "compilation errors". 
image
In my editor, I can already see warning and informations about my mistake. But this isn't typescript, and my editor still allows me to bundle something which will pitifully fail at the very first execution. 

But when we bundle the library, functions names are mangled and comments are removed in order to provide a minimal bundle size. 

So all those informations would then need to be stored in definition files (*.d.ts). With @JoeCoppola-HIA we were assessing types definitions from jsdoc. #189 

And this is how we met our `typescript` dev-dependency :)

When we build a version of three-mesh-ui, we would also run the command `tsc` which will extract all jsdoc to definition files.
Here is a preview. As you can see, our jsdoc is translated to typescript definition
image

**Is it really bad to stay with runtime errors only ?**
Actually, it is :) Emphasis : at least it might be. For our examples cases, it didn't really matter. We are able to instantly notice a runtime error.

But lets imagine that the instruction `getSquareRoot( "Bob" );` is called at the very last screen of our game project, and only if we beat the best score. We can of course add some cheatcode to go on the last screen, with the next best score. But in any case, it will consume more time than you editor telling you : "I won't compile that garbage instruction".


## glob
Only used to look on the example folder to automatically retrieve files that match a pattern
```js
// Automatically get all example.js files
const entryPoints = {};
glob.sync( './examples/*.js' ).map( function ( file ) {
	const entryKey = path.basename( file, '.js' );
	entryPoints[ entryKey ] = file;
} );
```
Im not sure about placing nodejs libraries into libs folder, as sometimes libraries and their dependencies depens on the user os and arch.

 ## karma, chai, mocha + reporters
If we agree I would remove those. I totally agree that unit tests are a winner, but we would be better if we could unit test jsm or even the source files itself. In the current setup, we won't be able to test code from example. I would give a try of jest in a near? future.

## acorn
patching a webpack version https://github.com/webpack/webpack/issues/13935

**Comment by felixmariotto** [comment]
I totally undestand your point for typescript and strict rules in general, after all this repo has become a true collaborative project so a bit of order is necessary, also following the industry standards is important. It's just that personally I'm a more "yolo" type of guy because I mainly work alone on short lived projects. But nevermind my own preferences, I have to adapt. 😊

**Comment by swingingtom** [comment]
I've added a task to cleanup dev-dependencies. Im going to merge this PR, and add more samples for 7.x.x

**Pull request merged**
