### PR TITLE
convert to ES classes

### PR DESCRIPTION
**Pull request by trusktr**
Alright, I started to get my feet wet!

For easier review, choose the `Hide whitespace changes` option in the `Files changed` tab. Maybe easier to check each commit separately.

Benefits:

1) More semantic with modern standards

2) Free intellisense powered by TypeScript in modern editors like Atom or VS Code. For example, the editor now knows where the methods come from, and can show documentation in tooltips (thanks to the JSDoc comments), go to definition, etc. Screenshot:

    Screenshot from 2020-06-13 15-26-31

3) Sets us up to eventually convert to TypeScript in the future if we want to

4) We can generate API docs from JSDoc comments.

### CODE REVIEW

**Comment by trusktr** [comment]
How important is supporting IE11? I say let's not! The new Chromium-based Edge is now the official browser of Windows 10, and the old Edge is now called Legacy Edge by default (in case anyone really really wants to use the old one).

**Comment by trusktr** [comment]
Alright, done! All demos are working.

I didn't convert `FontLibrary` into a class with static members, but I did convert `UpdateManager` to a class with static methods/props. So either I can change `UpdateMethod` back to just a module, or convert `FontLibrary` to a class with static methods/props. The only benefit would be nicer intellisense when things are grouped under a namespace (the name of the class) in intellisense visual output of editors (f.e. tooltips).

 Wdyt?

**Comment by trusktr** [comment]
What editor do you use? I suggest to take a look in VS Code at all the new intellisense that is visible.

**Comment by felixmariotto** [comment]
Thank you for handling this ! 

I'm not so fan of the es6 `class` syntax, but this is an open-source project, so I'm willing to forget my personal preference to comply with community standards 😊

Is there a specific reason why you didn't update all the comments, like [here](https://github.com/lume/three-mesh-ui/blob/c21ebdf95e6c9a1f075bbde92639dbe619d26e82/src/components/core/MeshUIComponent.js#L179) ?   
If not I think they should be updated too, for consistency sake.

> Either I can change UpdateMethod back to just a module, or convert FontLibrary to a class with static methods/props.

I don't mind one way or another.   
It seems you would rather convert FontLibrary to a class, if so then go for it.

> How important is supporting IE11?

Since this lib will primarily be used for VR GUI, I doubt IE11 support would be a highly requested feature, so let's not bother.

> What editor do you use?

I'm using Sublime Text 3, I like its minimalist interface. I will see if I can find an intellisense package for it.

**Comment by trusktr** [comment]
> Is there a specific reason why you didn't update all the comments, like here ?
> If not I think they should be updated too, for consistency sake.


Totally. I somehow missed those while I was flying through the files. Let me fix them.

> Since this lib will primarily be used for VR GUI, I doubt IE11 support would be a highly requested feature, so let's not bother.



Good point! 


> Sublime Text 3 


Looks like this is the official plugin: https://github.com/Microsoft/TypeScript-Sublime-Plugin

**Comment by trusktr** [comment]
I will circle back tonight and fix the conflicts.

**Comment by trusktr** [comment]
Alright, conflicts resolved! "tonight" was a bad estimate. It is late, I'll give everything a run tomorrow to make sure it works.

**Comment by felixmariotto** [comment]
I've tested, it looks like it works, I will merge and do some cleanup (you left a console.log I think and some comments must be converted). 

Yes I've installed the package, it's pleasant to code with the documentation on hovering the mouse. I've noticed that when you hover on a method that's not part of this mixin you don't have the doc. I guess it cannot be helped, surely the plugin is able to retrieve the method when using the built-in "class inheritance"... I still think it's more sustainable on the long run. Anyway at least one can know when a method is not part of this mixin, and knows they must find it elsewhere.

Thanks a lot for that !

**Comment by trusktr** [comment]
No prob! With some added types, it can become possible to have the methods from other mixins show up. We can use JSDoc comments , without any build step, and the intellisense would take advantage of it thanks to TypeScript's support for types via JSDoc comments. This is a step towards that. :) I can try a pass at that a little later.

**Comment by felixmariotto** [comment]
That would be awesome !

**Pull request merged**
