### PR TITLE
improve text antialiasing

### PR DESCRIPTION
**Pull request by felixmariotto**
So it's been a while I'm unsatisfied with how text is drawn on low res display (important for cheap VR heasets).
I referred to [the repo](https://github.com/Chlumsky/msdfgen#using-a-multi-channel-distance-field) of the original MSDF technic to get better distance field functions, and the result look really good !

## before:
not antialiased

## after:
antialiased

There is some artifacts when the character is really tiny, but it's still much better than before IMO.

### CODE REVIEW

**Comment by swingingtom** [comment]
Too bad we don't succeed to reproduce #93 on our side to check if this PR can solve it. 
Maybe #48 might be magically fixed ?

**Comment by felixmariotto** [comment]
I dug a bit more into the mysterious `pxRange` value. It looks like it is the value range of the distance field used in the generation of the msdf texture. For example if the value range is [ -1, 1 ], then `pxRange` is 2. On [msdfgen repo](https://github.com/Chlumsky/msdfgen#using-a-multi-channel-distance-field) they seem to use 4 as a default, same on [msdf-bmfont-xml](https://github.com/soimy/msdf-bmfont-xml), so in theory we could juste use a fixed value of 4.0 in the shader... But in practice there will be people wishing to use their own font files with different generation setting, so it must be set in a uniform.

**Comment by felixmariotto** [comment]
I looked for quite a long time in the msdfgen repo for a better implementation, but everytime someone ask for it Chlumsky writes that the snippet in msdfgen's readme is just an example and that people "should do their homework and figure out the best implementation by themselves".

**Comment by felixmariotto** [comment]
This PR is literally a copy paste of the [example they give on their readme](msdfgen)

**Comment by hybridherbst** [comment]
I fully agree - after testing a bit more I think the difference comes from his samples all using pixel-perfect snapping which obviously doesn't work in 3D space, and then the quality quickly degrading when things are not snapped anymore. Sorry if this came over as critizizing your implementation, wasn't meant like that, I also compared it with his reference.

So maybe there are improvements to be made for these sub-pixel scenarios, as they are 99% of what happens in VR, but that's probably another thesis :D

**Comment by hybridherbst** [comment]
Hi again, Chlumsky was so nice and has provided a WebGL demo that shows ground-truth MSDF text in 3D (without supersampling): https://chlumsky.appspot.com/msdf-demo. This should help to compare/find remaining issues, if any.

I also attached the HTML file in case the live demo gets lost: [MSDF text rendering demo.zip](https://github.com/felixmariotto/three-mesh-ui/files/7900652/MSDF.text.rendering.demo.zip)

**Comment by hybridherbst** [comment]
I think the difference it's that it still looks better / crisper, but may be the mipmaps change that already?

The pxRange as parameter should perhaps have a more verbose name (related to the font), and I think the unitRange should be precomputed instead of being calculated from texture size + pxRange in the shader.

**Comment by felixmariotto** [comment]
> I think the difference it's that it still looks better / crisper, but may be the mipmaps change that already?
Yes now without the mipmaps and with RGSS enabled it looks really good, even in VR. Disabling mips removed the last artifacts.

**Comment by felixmariotto** [comment]
> The pxRange as parameter should perhaps have a more verbose name (related to the font), and I think the unitRange should be precomputed instead of being calculated from texture size + pxRange in the shader.

I tried to do this but there is clearly an issue in the MaterialManager module, it must be refactored before to undertake this.
I will open an issue to propose this refactor and link to this optimization.

**Comment by hybridherbst** [comment]
There might still be some details different; at very small font sizes Chlumsky's demo looks a lot better, maybe wrong sharpening on our end:
(RGSS improves it but the baseline is not as clean)

his:
image

ours:
image

**Comment by hybridherbst** [comment]
and I'd replace "big texts" with "large font sizes" as "big text" is literally another example with a different meaning ("lots of text")

**Comment by hybridherbst** [comment]
@felixmariotto not sure if you saw my comments here, should I make a new issue for remaining text problems?

**Comment by felixmariotto** [comment]
@hybridherbst yes please make a new issue.

**Pull request merged**
