### PR TITLE
added ability to add preloaded fonts, added example of preloaded font

### PR DESCRIPTION
**Pull request by corecode1**

### CODE REVIEW

**Comment by felixmariotto** [comment]
Awesome !

It would be even better if you could update your example's text to something explaining the purpose of the example. I mean the 3D text in the generated panel, which is currently _"This library supports line-break-friendly-characters..."_.  

Something like _"This example shows how to use pre-loaded font files."_, or anything else ?

It's really useful, nice from you to add this feature.

**Comment by felixmariotto** [comment]
related issue : #42

**Comment by corecode1** [comment]
@felixmariotto updated panel text to: 

This example shows how to use pre-loaded font files
You can preload font or font and texture, and add it to FontLibrary!
After that, all added text of this font will be displayed with no loading delays!

**Comment by felixmariotto** [comment]
OK, it's merged and published to NPM ( version 4.4.0 ).  
Thanks again !

**Pull request merged**
