### PR TITLE
(7.x.x) - Unit Tests : Data oriented proposal

### PR DESCRIPTION
**Pull request by swingingtom**
This PR try to demonstrate what can already be done from a data oriented side.

Proposal only demonstrate a first content-direction tests, which checks children block properties are correctly updated when switching `.contentDirection` property on their parent block.

Proposal use a karma+mocha+chai setup, but that can be change.

### Unable to use import
I didn't succeed to import js files from test files. I had then to fallback on loading UMD builds of three and three-mesh-ui

### Test setup repeats
As I wasn't able to import file, the threejs scene initialisation in [before()](https://github.com/felixmariotto/three-mesh-ui/blob/edc6e8c1d8da9e8fd0bcebe82ae40a71bb9d0f48/tests/block-layout/content-direction.js#L7) might need to be repeated on each file.

### Coverage
As I wasn't able to import file, the only coverage I was able to provide, is the coverable of the three-mesh-ui built which is not totally revelant as it include webpack lines.

### Fixes in three-mesh-ui
As I wasn't able to import file, each fixes on three-mesh-ui require a new build `$ npm run build` before next test run

### Readability
The [content-direction test](https://github.com/felixmariotto/three-mesh-ui/blob/7.x.x-feature/unit-test-initialisation/tests/block-layout/content-direction.js) isn't really huge, but I find that this readability should be better, but don't know how.

Forks and PR more than welcome to provide a better data-oriented test setup

### CODE REVIEW

**Comment by eviltik** [comment]
Excellent.

The architecture is quite flexible. The depth of the tests is not limited, judiciously chosen.

### Unable to use import

IIs this still the case? thinking about #187 

### Tests prioritization proposal
* Continuous integration tests : guarantee that all examples always work without js fatal errors due to a perfectible commit. Simple CI test.

* Unit tests ( like your proposal ). 

### Unit tests: steps proposal

What about adding a specific comment there ( `TEST`: `todo` | `done` ) where it is needed in all the codes ? example

```
/**
* Called by Text to get the dimensions of a particular glyph,
* in order for InlineManager to compute its position
* @TEST: todo | done
*/
getGlyphDimensions( options ) {
```

Someone (you?) could then go through the code looking for the right methods to test. 
Then someone else can pick and implement a test in `todo` status.
Once implemented, the `TEST` value changes to `done`. 
Thus, any contributor will also know that there is a test associated with the method they are modifying.

What do you think ?

**Comment by swingingtom** [comment]
> IIs this still the case? thinking about https://github.com/felixmariotto/three-mesh-ui/issues/187

It is, unfortunately. This isn't related to three-mesh-ui, but from karma. I hadn't succeed with posts/tutorials I followed. I would welcome any help that could lead to import source files instead of bundles.

> Unit tests: steps proposal

I like the idea. I like a bit less the `done` status (specifically for unit tests). What about a location information instead ? 
```javascript
/**
*
* @Tests tests/msdf/glyphs.test.js
*/
getGlyphDimensions( options ) {
```

**Comment by eviltik** [comment]
+1 for location information

Ok for karma, let me try

**Comment by swingingtom** [comment]
I managed to get some improvements, even if that doenst completely solve everything, at least it looks a bit less clunky.

## Unable to use import
Not `totally` the case anymore. I didnt succeed to load `/src/three-mesh-ui.js` as it would be better for coverage, but I managed load additional test setup files. 

## Test setup repeats
A bit better now with imports enable and destructuring
```javascript
import { buildThreeSetup } from '../../../utils/TestThree.js' ;
import { preloadFonts } from '../../../utils/TestFonts.js';

describe("ContentDirection", function () {

	let scene, camera, renderer, render;
	let fontFamily;

	before( function (done) {
		({scene, camera, renderer, render} = buildThreeSetup());
		fontFamily = preloadFonts( done );
	});
});
```

instead of previously
```javascript
describe("ContentDirection", function () {

	let scene, camera, renderer, render;
	let fontFamily;

	before(function (done) {

		scene = new THREE.Scene();

		const WIDTH = window.innerWidth;
		const HEIGHT = window.innerHeight;
		camera = new THREE.PerspectiveCamera( 60, WIDTH / HEIGHT, 0.1, 100 );

		renderer = new THREE.WebGLRenderer();
		renderer.setPixelRatio( window.devicePixelRatio );
		renderer.setSize( WIDTH, HEIGHT );

		document.body.appendChild( renderer.domElement );

		camera.position.set( 0, 1.6, 0 );

		render = () => {
			ThreeMeshUI.update();
			renderer.render( scene, camera );
		}

		// load fonts
		ThreeMeshUI.FontLibrary.prepare(
			ThreeMeshUI.FontLibrary
				.addFontFamily("Roboto")
				.addVariant('400','normal', "/base/examples/assets/fonts/msdf/roboto/regular.json", "/base/examples/assets/fonts/msdf/roboto/regular.png")
		).then( done );


	});
});

```

## Coverage
Still not that great as it cover a webpack built file.

### Fixes in three-mesh-ui
Some command has been added in order to run tests automatically when bundles are built.

**Pull request merged**
