### PR TITLE
remove useless updates

### PR DESCRIPTION
**Pull request by felixmariotto**
@GoncaloBastos found a way to improve performance in #122. As it's unrelated to this PR I'm creating a new one with this small change.

We will ignore attribute updates if the new value is the same as the previous value, which might indeed improve performance in some cases.

### CODE REVIEW

**Review by swingingtom — COMMENTED** [review]
Do you think it is helpful to keep the conversion enabled rather than preventing it with a strict equality ?

**Comment by swingingtom** [comment]
Don't bother with that, but when passing non primitive values such as borderRadius, they will still trigger an update. 

```javascript
panel.set({
		borderRadius: [0, 0.2 + 0.2 * Math.sin( Date.now() / 500 ), 0, 0],
	});
```

Which may only represents a few cases. Go for it

**Comment by felixmariotto** [comment]
We could do this to check for equality of non primitives :
`if ( JSON.stringify(this[prop]) == JSON.stringify(options[prop]) ) continue`

I suppose it has a performance impact but I'm not sure if we can ignore it or not.

**Comment by swingingtom** [comment]
Not sure it worth the shot.

**Comment by GoncaloBastos** [comment]
Yeah the idea is to improve performance, so its probably not worth it. I'd say avoiding updates for primitives is already pretty good. It can always be revisited in the future if further improvements are needed.

**Comment by swingingtom** [comment]
Agreed. It should cover >90% of available properties

**Review by GoncaloBastos — APPROVED** [review]

**Comment by felixmariotto** [comment]
thanks !

**Pull request merged**
