### PR TITLE
Fix letter spacing next line break

### PR DESCRIPTION
**Pull request by swingingtom**
There was the artefact that was causing that. 
I replayed all examples, everything seems up again.

### CODE REVIEW

**Comment by felixmariotto** [comment]
oops I should have checked better, thanks for the quick fix.
I also fixed a bug I introduced while linting in your example.. didn't notice your where reassigning `letterSpacingSpeed`..
Just curious, are you working with HIA Technologies ?

**Comment by JoeCoppola-HIA** [comment]
I do not recognize @swingingtom, but I work over at HIA @felixmariotto. Is there anything I can do for you? Thanks @swingingtom for this awesome feature addition.

**Comment by felixmariotto** [comment]
@JoeCoppola-HIA actually I was just wondering, I know you guys use three-mesh-ui for one of your project and I understood that you wanted to contribute at some point. Since @swingingtom is in a row I thought they might work with you. Sheer curiosity !

**Comment by JoeCoppola-HIA** [comment]
Hey @felixmariotto, all good! We for sure want to contribute, just rapidly approaching some deadlines at the year end. Was actually looking into the frame shadow casting a little today. Hope to have some stuff for you in the upcoming year!

**Comment by swingingtom** [comment]
As @JoeCoppola-HIA said, Im not working in HIA team. At least for now ;)

> oops I should have checked better, thanks for the quick fix.

Same applies for myself. I might have been confused by the fact that I've three live examples pages open, official, forked and localhost. Anyways, its a good reminder to be cautious.

**Pull request merged**
